lukas-kirschner/Exodus

src/game/player.rs

This is more similar to how jumping in the original game worked

Make jumps go two squares left/right instead of just one

---

src/main.rs

Fixed Texture Atlas Bleeding

---

src/game/constants.rs
src/game/mod.rs
src/game/pickup_item.rs
src/game/tilewrapper.rs
src/game/world.rs

Implemented a Collectible Pickup Animation

---

Cargo.lock
Cargo.toml
src/egui_textures.rs
src/game/camera.rs
src/game/constants.rs
src/game/player.rs
src/game/scoreboard.rs
src/game/tilewrapper.rs
src/game/ui.rs
src/game/world.rs
src/main.rs
src/mapeditor/mapeditor_ui.rs
src/mapeditor/mod.rs
src/mapeditor/player_spawn.rs
src/mapeditor/preview_tile.rs
src/mapselectionscreen.rs
src/uicontrols.rs

Updated to Bevy 0.9, debloated Bevy Binary Size

---

src/game/player.rs

Implemented World Boundary Collision Checks

---

src/game/player.rs

Fixed Ladders

---

libexodus/src/tiles.rs
libexodus/src/world/exampleworlds.rs
libexodus/src/world/mod.rs
src/game/pickup_item.rs
src/game/player.rs

Implemented Arrows

---

.idea/runConfigurations/Test.xml
Cargo.lock
libexodus/Cargo.toml
libexodus/src/directions.rs
libexodus/src/tiles.rs
libexodus/src/world/io.rs
libexodus/src/world/io_error.rs
libexodus/src/world/mod.rs

28 better map format

---

.gitlab-ci.yml
src/game/pickup_item.rs
src/mapeditor/mapeditor_ui.rs

1 change collecting collectibles to trigger an event

---

Cargo.lock
libexodus/Cargo.toml
libexodus/src/world/exampleworlds.rs
libexodus/src/world/hash.rs
libexodus/src/world/io.rs
libexodus/src/world/io_error.rs
libexodus/src/world/mod.rs
src/dialogs/save_file_dialog.rs
src/main.rs
src/mapeditor/mapeditor_ui.rs
src/mapselectionscreen.rs

47 implement guid hashing of maps

---

src/mapeditor/mod.rs

Changed Viewport To World to use new Bevy 0.9 Features

---

README.md
libexodus/src/tiles.rs
src/game/camera.rs
src/game/constants.rs
src/game/player.rs
src/game/world.rs
src/main.rs
src/mapeditor/edit_world.rs
src/mapeditor/mod.rs
src/mapeditor/player_spawn.rs
src/mapeditor/preview_tile.rs

Textures are finally not bleeding anymore

58 render image before upscaling to stop texture bleeding

---

src/game/camera.rs
src/game/constants.rs
src/game/pickup_item.rs
src/game/player.rs
src/game/world.rs
src/mapeditor/edit_world.rs
src/mapeditor/mod.rs
src/mapeditor/player_spawn.rs
src/mapeditor/preview_tile.rs

Fixes #66 
Fixes #60 
Fixes #56 
Workaround for #44

Completely reworked the way cameras scale the world. Fixed Translation and Scaling of Map in UI Viewport.

---

libexodus/src/world/mod.rs
src/animation/animated_action_sprite.rs
src/animation/mod.rs
src/campaign/campaign_trail.rs
src/game/constants.rs
src/game/pickup_item.rs
src/game/player.rs
src/game/scoreboard.rs
src/game/tilewrapper.rs
src/main.rs
src/mapeditor/edit_world.rs
src/ui/game_over_screen.rs

fixes #85 
fixes #83 
fixes #71 
fixed #84

Implemented common animation plugin for all player and collectible animations. Fixed bugs in Player Spawn Placement and Campaign Launch

---

src/game/constants.rs
src/game/pickup_item.rs
src/game/player.rs

Key used animation

---

Cargo.lock
Cargo.toml
libexodus/src/campaign/graph.rs
src/campaign/campaign_map_asset_loader.rs
src/campaign/campaign_maps.rs
src/campaign/campaign_trail_asset_loader.rs
src/campaign/mod.rs
src/game/camera.rs
src/game/pickup_item.rs
src/game/player.rs
src/game/scoreboard.rs
src/game/ui.rs
src/main.rs
src/mapeditor/mapeditor_ui.rs
src/textures/egui_textures.rs
src/textures/mod.rs
src/textures/tileset_manager.rs
src/ui/mod.rs

Upgraded Bevy to 0.12

---

Cargo.lock
Cargo.toml
locales/de_DE.yml
locales/en_US.yml
src/dialogs/create_new_map_dialog.rs
src/dialogs/delete_map_dialog.rs
src/dialogs/edit_message_dialog.rs
src/dialogs/mod.rs
src/dialogs/save_file_dialog.rs
src/textures/fonts.rs
src/ui/mapselectionscreen.rs
src/ui/mod.rs

Implemented Delete map dialog

---

assets/textures/tilesets/Antarctica.png
assets/textures/tilesets/Classic.png
assets/textures/tilesets/Tiny_Platform_Quest_Tiles.png
libexodus/src/tiles.rs
libexodus/src/world/io.rs
locales/de_DE.yml
locales/en_US.yml
src/mapeditor/mapeditor_ui.rs

Implemented Cobblestone Roof Tiles

---

src/textures/fonts.rs
src/textures/mod.rs
src/ui/mainmenu.rs
src/ui/mapselectionscreen.rs
src/ui/uicontrols.rs

98 UI improvements

---

.idea/runConfigurations/Test.xml
Cargo.lock
Cargo.toml
libexodus/Cargo.toml
libexodus/src/tilesets/mod.rs
src/animation/animated_action_sprite.rs
src/campaign/campaign_map_asset_loader.rs
src/campaign/campaign_maps.rs
src/campaign/campaign_trail.rs
src/campaign/campaign_trail_asset_loader.rs
src/campaign/mod.rs
src/dialogs/create_new_map_dialog.rs
src/dialogs/save_file_dialog.rs
src/game/mod.rs
src/game/player.rs
src/game/vending_machine.rs
src/game/world.rs
src/main.rs
src/mapeditor/mapeditor_ui.rs
src/mapeditor/player_spawn.rs
src/mapeditor/preview_tile.rs
src/textures/egui_textures.rs
src/textures/mod.rs
src/ui/configscreen.rs
src/ui/mainmenu.rs

116 upgrade to bevy 014
